use_frameworks!

platform :ios, '9.0'

target 'ThreeDWallpaperSDK_Example' do
  pod 'ThreeDWallpaperSDK', :path => '../'

  target 'ThreeDWallpaperSDK_Tests' do
    inherit! :search_paths

    
  end
end
